### ISSUE TITLE
Feature: Add option to prevent downloading tracks which already exist in target directory

### ISSUE THREAD

**Issue by artus70** [timschneeb/KomootGPX#11]
First: Thanks for the nice script!

I'd like to download "all" tracks at once but skip those tracks which already have been downloaded before - in order to only download new tracks and therefore complete my local backup. 

Is there - or could be - an option for that?

**Comment by marcin-gryszkalis** [comment]
Great idea, it would be pretty simple adding some `if os.path.exists(path)`. I'll make a patch.

**Comment by marcin-gryszkalis** [comment]
Option added https://github.com/timschneeb/KomootGPX/pull/12

**Comment by artus70** [comment]
Thanks a lot - but now I've to ask you for help, for I'm not used to work with pip:

On macos, I try to use `pipx upgrade komootgpx`, but I get the message "komootgpx is already at latest version 1.1.2". What do I have to do in order to install the latest code?

**Comment by timschneeb** [comment]
Please try again to run that command again. I've created a new release tag and uploaded new Python packages to pypi.org.

**Comment by artus70** [comment]
Got it to work now, thanks!!!
