### ISSUE TITLE
Unknown tour id selected

### ISSUE THREAD

**Issue by backupandforkacc** [timschneeb/KomootGPX#7]
Thank you for the code. 

Unfortunately, I only get this error message:

```
Logging in...
Logged in as 'XXX' <= censored
Interactive mode. Use '--help' for usage details.
Found 1 tours

1126933058 => Dreifaltigkeitskirche Kappl – Feisnitz Stausee Runde von Marktredwitz (touringbicycle; 51.035km; tour_planned)

Enter a tour id to download
>3319445

Fetching tours of user '3375363794682'...
Found 1 tours
Unknown tour id selected. These are all available tours on your profile:
Found 1 tours

1126933058 => Dreifaltigkeitskirche Kappl – Feisnitz Stausee Runde von Marktredwitz (touringbicycle; 51.035km; tour_planned)
```

So what are the restrictions of your code?

The ID is certainly correct, see:
https://www.komoot.de/smarttour/3319445

**Comment by marcin-gryszkalis** [comment]
the route you mentioned is so called "Smart Tour", they are automatically generated by komoot using highlight and users' suggestions. To be able to export such route you first need to click "save" button - the smart tour will be copied to your own routes and then you will see it on your list (and be able to export).
